package com.smartgwt.logicalstructure.widgets.chart;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class FacetChartLogicalStructure extends DrawPaneLogicalStructure {
    public String autoRotateLabels;
    public String backgroundBandProperties;
    public String bandedBackground;
    public String barMargin;
    public String barProperties;
    public String chartRectMargin;
    public String chartRectProperties;
    public String chartType;
    public String clusterMarginRatio;
    public CellRecord[] dataAsCellRecordArray;
    public String dataAsString;
    public String dataAxisLabelProperties;
    public String[] dataColors;
    public String dataLabelProperties;
    public String dataLineProperties;
    public String dataMargin;
    public String dataOutlineProperties;
    public String dataPointProperties;
    public String dataPointSize;
    public String dataShapeProperties;
    public String decimalPrecision;
    public String doughnutHoleProperties;
    public String doughnutRatio;
    public String[] extraAxisMetrics;
    public MetricSettings[] extraAxisSettings;
    public Facet[] facetsAsFacetArray;
    public String facetsAsString;
    public String filled;
    public String gradationLabelProperties;
    public String gradationLineProperties;
    public String gradationTickMarkLength;
    public String gradationZeroLineProperties;
    public String hoverLabelProperties;
    public String legendItemPadding;
    public String legendLabelProperties;
    public String legendMargin;
    public String legendPadding;
    public String legendRectProperties;
    public String legendSwatchProperties;
    public String legendSwatchSize;
    public String legendTextPadding;
    public String logBase;
    public String[] logGradations;
    public String logScale;
    public String maxBarThickness;
    public String minBarThickness;
    public String pieBorderProperties;
    public String pieLabelAngleStart;
    public String pieLabelLineExtent;
    public String pieLabelLineProperties;
    public String pieRingBorderProperties;
    public String pieSliceProperties;
    public String radarBackgroundProperties;
    public String radialLabelOffset;
    public String shadowProperties;
    public String showChartRect;
    public String showDataAxisLabel;
    public String showDataPoints;
    public String showDataValues;
    public String showDoughnut;
    public String showLegend;
    public String showRadarGradationLabels;
    public String showScatterLines;
    public String showShadows;
    public String showTitle;
    public String showValueAxisLabel;
    public String showValueOnHover;
    public String stacked;
    public String styleName;
    public String tickMarkToValueAxisMargin;
    public String title;
    public String titleProperties;
    public String useAutoGradients;
    public String useLogGradations;
    public String valueAxisLabelProperties;
    public String valueAxisMargin;
    public String valueLineProperties;
    public String valueProperty;
    public String valueTitle;
    public String xAxisMetric;
    public String yAxisMetric;
}



