
package com.smartgwt.client.docs;

/**
 * <h3>Custom Querying Overview</h3>
 * <b>This feature is available with Power or better licenses only.</b> See &#010 <a
 * href="http://smartclient.com/product">smartclient.com/product</a> for details.&#010 <p>&#010 The Smart GWT server
 * provides a number of ways to let you customize the SQL or Hibernate&#010 query it generates to fetch data from or update
 * your database.  You can provide full &#010 custom queries in either {@link
 * com.smartgwt.client.docs.serverds.OperationBinding#customSQL SQL} or &#010 {@link
 * com.smartgwt.client.docs.serverds.OperationBinding#customHQL HQL}, or you can replace individual parts of the query
 * &#010 ({@link com.smartgwt.client.docs.serverds.OperationBinding#whereClause the WHERE clause}, for example) while
 * letting&#010 Smart GWT generate the rest.  Full custom queries provide complete flexibility, but &#010 they cannot be
 * used for automatic data paging; if you use a full custom query, all of its&#010 data will be returned to the client in
 * one shot.  This may, of course, be perfectly &#010 reasonable, depending on the number of rows involved.  However, if
 * you need automatic &#010 paging support, you should try to implement your customizations by replacing pieces of the&#010
 * query.&#010 <p>&#010 Query customization is done per {@link com.smartgwt.client.data.OperationBinding}, so it is
 * entirely feasible to &#010 provide multiple custom queries for the same {@link
 * com.smartgwt.client.data.OperationBinding#getOperationType operation type} &#010 on a given {@link
 * com.smartgwt.client.data.DataSource}.&#010&#010 <h4>Using criteria and values</h4>&#010 Whether using full custom
 * queries or individual clauses, your code has access to the &#010 criteria values submitted with the operation; if this
 * is an "add" or "update" operation,&#010 it also has access to the new field values sent from the client.&#010 <p>&#010
 * Fields are accessed in your SQL or HQL code using the Velocity template language.  You&#010 can refer to container
 * variables <b>$criteria</b> and <b>$values</b> in your queries or &#010 clause snippets, and Smart GWT will insert the
 * appropriate values.  A simple &#010 {@link com.smartgwt.client.docs.serverds.OperationBinding#whereClause whereClause}
 * example:&#010 <p>&#010 <pre><code>&#010  &lt;operationBinding &#010         operationType="fetch"&#010        
 * whereClause="continent = $criteria.continent AND population &gt; $criteria.minPop"&#010  /&gt;&#010 </code></pre>&#010
 * &#010 <h4>Other template variables</h4>&#010 In addition to the Velocity template variables described above, we also
 * provide a number of&#010 template variables containing generally-useful values.  Please see&#010 {@link
 * com.smartgwt.client.docs.VelocitySupport} for details.&#010&#010 <h4>Using the default clauses</h4>&#010 You also have
 * access to the  default subclauses generated by &#010 Smart GWT.  You can use these in full custom queries to allow a
 * certain part of the query&#010 code to be generated:<p>&#010 <code>SELECT foo, bar FROM $defaultTableClause WHERE baz >
 * $criteria.baz</code>.  &#010 <p>&#010 You can also use them, with care, as a foundation for your own additions:<p>&#010
 * <code>SELECT $defaultSelectClause, foo, bar FROM $defaultTableClause WHERE ($defaultWhereClause) AND baz >
 * $criteria.baz</code>.&#010 <p>&#010 You can also use them within query snippets in the various subclause
 * properties:<p>&#010 <code>&lt;selectClause&gt;$defaultSelectClause, foo, bar&lt;/selectClause&gt;</code>&#010 &#010
 * <h4>Velocity Template Language conditional logic</h4>&#010 When writing a customize a SQL clause for an operation, it is
 * commonly desirable to be&#010 able to include conditional logic - for example only modifying a where clause if a&#010
 * certain criteria value is present. Velocity template language conditional statements&#010 can be embedded directly into
 * your template code to achieve this. For example the following&#010 <code>whereClause</code> would produce different
 * output depending on whether the &#010 request criteria included a value for the field
 * <code><i>someField</i></code>:<p>&#010 <code>&lt;whereClause&gt;$defaultWhereClause #if ($criteria.someField) AND
 * someDatabaseField = $criteria.someField #end&lt/whereClause&gt;</code>&#010 <p>&#010 If
 * <code><i>criteria.someField</i></code> was not present in the request, the generated&#010 SQL statement would simply use
 * the default where clause -- otherwise&#010 <code>AND someDatabaseField = <i>[some value]</i></code> would be appended to
 * it (where&#010 <code><i>[some value]</i></code> was picked up from value of <code>someField</code> on &#010 the request
 * criteria object).&#010 <p>&#010&#010 <h4>Stored procedures</h4>&#010 It is possible to include templated calls to SQL
 * stored procedures in a&#010 {@link com.smartgwt.client.docs.serverds.OperationBinding#customSQL customSQL} clause, for
 * the ultimate in flexibility.  For &#010 example, the deletion of an order might require a number of actions: deletion of
 * the order&#010 record itself, messages sent to other systems (data warehousing, maybe, or a central accounts&#010 system
 * running on a mainframe), an event log written, and so on.  You could write a stored &#010 procedure to do all this, and
 * then invoke it with a customSQL clause:&#010 <pre>&#010    &lt;operationBinding operationType="remove"&gt;&#010       
 * &lt;customSQL&gt;call deleteOrder($criteria.orderNo)&lt;/customSQL&gt;&#010    &lt;/operationBinding&gt;&#010
 * </pre>&#010 <h4>Custom queries are safe</h4>&#010 Custom queries are protected from <a
 * href=http://en.wikipedia.org/wiki/SQL_injection>&#010 SQL injection attacks</a>, because anything coming from the client
 * is quoted and escaped &#010 in accordance with the syntax of the underlying database before use (though see the
 * warning&#010 about using <code>$rawValue</code> in the article on {@link
 * com.smartgwt.client.docs.VelocitySupport}).&#010 So, in a typical SQL injection attack an attacker might enter his User
 * ID as <br>&#010 &nbsp;&nbsp;<code>123' OR '1' = '1</code><p>&#010 in the hope that this will generate a query&#010 with
 * a where clause like this<br>&#010  &nbsp;&nbsp;<code>WHERE userID = '123' OR '1' = '1'</code><p>&#010 which would of
 * course return every row.  With Smart GWT custom queries, this does not happen; &#010 the client-provided string is
 * escaped, and the resultant clause would look like this: <br>&#010 &nbsp;&nbsp;<code>WHERE userID = '123'' OR ''1'' =
 * ''1'</code><p>&#010 This clause only returns those records where the userID column contains the literal value that &#010
 * the user typed: <br>&#010 &nbsp;&nbsp;<code>123' OR '1' = '1</code>&#010 <p>&#010 Further, custom queries can be
 * protected from buggy or ad-hoc client requests because the &#010 query is specified on the server.  For example you
 * could add a custom where clause, as shown&#010 in the above section on default clauses, to ensure that certain records
 * are never seen by&#010 the client.  For instance: <p>&#010 <code>&lt;whereClause&gt;($defaultWhereClause) AND
 * confidential = '0'&lt;/whereClause&gt;</code>.
 * @see com.smartgwt.client.docs.serverds.OperationBinding#selectClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#tableClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#whereClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#groupClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#orderClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#valuesClause
 * @see com.smartgwt.client.docs.serverds.OperationBinding#customSQL
 * @see com.smartgwt.client.docs.serverds.OperationBinding#customHQL
 * @see com.smartgwt.client.docs.serverds.OperationBinding#customFields
 * @see com.smartgwt.client.docs.serverds.OperationBinding#customValueFields
 * @see com.smartgwt.client.docs.serverds.OperationBinding#customCriteriaFields
 * @see com.smartgwt.client.docs.serverds.OperationBinding#excludeCriteriaFields
 * @see com.smartgwt.client.docs.serverds.OperationBinding#useForCacheSync
 * @see com.smartgwt.client.docs.serverds.OperationBinding#cacheSyncOperation
 * @see com.smartgwt.client.docs.serverds.OperationBinding#canSyncCache
 * @see com.smartgwt.client.docs.serverds.OperationBinding#sqlType
 * @see com.smartgwt.client.types.SQLType
 */
public interface CustomQuerying {
}
