
package com.smartgwt.client.docs;

/**
 * The following APIs are all related to DataType.
 * @see com.smartgwt.client.data.DataSourceField#getRequired
 * @see com.smartgwt.client.data.DataSourceField#getAutoGenerated
 * @see com.smartgwt.client.data.DataSourceField#getNillable
 * @see com.smartgwt.client.data.DataSourceField#getValueMap
 * @see com.smartgwt.client.data.DataSourceField#getValidators
 * @see com.smartgwt.client.data.DataSourceField#getLength
 * @see com.smartgwt.client.data.SimpleType#getValueMap
 */
public interface DataType {
}
