package com.smartgwt.logicalstructure.widgets;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class WindowLogicalStructure extends VLayoutLogicalStructure {
    public String animateMinimize;
    public String autoCenter;
    public String autoSize;
    public String bodyColor;
    public String bodyDefaults;
    public String bodyStyle;
    public String canDragReposition;
    public String canDragResize;
    public String canFocusInHeaderButtons;
    public String contentLayout;
    public String contentsType;
    public String defaultMinimizeHeight;
    public String dismissOnEscape;
    public String dismissOnOutsideClick;
    public String[] footerControls;
    public String footerHeight;
    public String[] headerControls;
    public String headerIconDefaults;
    public String headerSrc;
    public String headerStyle;
    public String hiliteBodyColor;
    public String hiliteHeaderSrc;
    public String hiliteHeaderStyle;
    public String isModal;
    public String keepInParentRectAsString;
    public String maximized;
    public String minimizeAcceleration;
    public String minimized;
    public String minimizeHeight;
    public String minimizeTime;
    public String modalMaskOpacity;
    public String modalMaskStyle;
    public String opacity;
    public String showBody;
    public String showCloseButton;
    public String showFooter;
    public String showHeader;
    public String showHeaderBackground;
    public String showHeaderIcon;
    public String showMaximizeButton;
    public String showMinimizeButton;
    public String showModalMask;
    public String showResizer;
    public String showStatusBar;
    public String showTitle;
    public String src;
    public String status;
    public String title;
    public String useBackMask;
}



