isc.DataSource.create({
    ID:"Validator",
    addGlobalId:"false",
    fields:{
        type:{type:"string"},
        stopIfFalse:{type:"boolean"},
        clientOnly:{type:"boolean"},
        errorMessage:{type:"string"},
        max:{type:"number"},
        min:{type:"number"},
        mask:{type:"regexp"},
        transformTo:{type:"regexp"},
        precision:{type:"integer"},
        expression:{type:"string"},
        otherField:{type:"string"},
        list:{multiple:"true", type:"text"},
        valueMap:{type:"ValueMap"},
        substring:{type:"text"},
        operator:{type:"text"},
        count:{type:"integer"}
    }
})
