package com.smartgwt.logicalstructure.widgets.layout;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class LayoutLogicalStructure extends CanvasLogicalStructure {
    public String alignAsString;
    public String animateMembers;
    public String animateMemberTime;
    public String canDropComponents;
    public String defaultLayoutAlignAsString;
    public String defaultResizeBars;
    public String dropLineThickness;
    public String enforcePolicy;
    public String hPolicy;
    public String layoutBottomMargin;
    public String layoutLeftMargin;
    public String layoutMargin;
    public String layoutRightMargin;
    public String layoutTopMargin;
    public String leaveScrollbarGap;
    public String locateMembersBy;
    public String locateMembersType;
    public String managePercentBreadth;
    public String memberOverlap;
    public Canvas[] members;
    public String membersMargin;
    public String minMemberSize;
    public String overflow;
    public String paddingAsLayoutMargin;
    public String placeHolderDefaults;
    public String placeHolderProperties;
    public String resizeBarClass;
    public String resizeBarSize;
    public String reverseOrder;
    public String showDragPlaceHolder;
    public String showDropLines;
    public String stackZIndex;
    public String vertical;
    public String vPolicy;
}



