package com.smartgwt.logicalstructure.widgets.calendar;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class CalendarLogicalStructure extends CanvasLogicalStructure {
    public String addEventButtonHoverText;
    public String baseStyle;
    public String cancelButtonTitle;
    public String canCreateEvents;
    public String canDeleteEvents;
    public String canDragEventField;
    public String canDragEvents;
    public String canEditEvents;
    public String canEditField;
    public String canEditLane;
    public String canResizeTimelineEvents;
    public String chosenDate;
    public String currentViewName;
    public CalendarEvent[] data;
    public String dataFetchMode;
    public String dateEditingStyle;
    public String dateFormatter;
    public String datePickerHoverText;
    public String dayBodyBaseStyle;
    public String dayHeaderBaseStyle;
    public String dayViewTitle;
    public String descriptionField;
    public String detailsButtonTitle;
    public String disableWeekends;
    public String endDate;
    public String endDateField;
    public String eventAutoArrange;
    public FormItem[] eventDialogFields;
    public String eventDragGap;
    public FormItem[] eventEditorFields;
    public String eventNameFieldTitle;
    public String eventOverlap;
    public String eventOverlapIdenticalStartTimes;
    public String eventOverlapPercent;
    public String eventSnapGap;
    public String eventWindowStyle;
    public String eventWindowStyleField;
    public String firstDayOfWeek;
    public HeaderLevel[] headerLevels;
    public String invalidDateMessage;
    public ListGridField[] laneFields;
    public String laneNameField;
    public Lane[] lanes;
    public String leadingDateField;
    public String monthViewTitle;
    public String nameField;
    public String nextButtonHoverText;
    public String otherDayBlankStyle;
    public String otherDayBodyBaseStyle;
    public String otherDayHeaderBaseStyle;
    public String previousButtonHoverText;
    public String rowHeight;
    public String saveButtonTitle;
    public String scrollToWorkday;
    public String selectedCellStyle;
    public String showControlsBar;
    public String showDateChooser;
    public String showDayHeaders;
    public String showDetailFields;
    public String showEventDescriptions;
    public String showOtherDays;
    public String showQuickEventDialog;
    public String showTimelineView;
    public String showWeekends;
    public String showWorkday;
    public String sizeEventsToGrid;
    public String startDate;
    public String startDateField;
    public String timeFormatter;
    public String timelineGranularity;
    public String timelineUnitsPerColumn;
    public String timelineViewTitle;
    public String todayBackgroundColor;
    public String trailingDateField;
    public String weekEventBorderOverlap;
    public String weekViewTitle;
    public String workdayBaseStyle;
    public String workdayEnd;
    public String workdays;
    public String workdayStart;
}



