package com.smartgwt.logicalstructure.widgets.tree;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class TreeGridLogicalStructure extends ListGridLogicalStructure {
    public String animateFolderEffect;
    public String animateFolderMaxRows;
    public String animateFolders;
    public String animateFolderSpeed;
    public String animateFolderTime;
    public String autoFetchTextMatchStyle;
    public String canAcceptDroppedRecords;
    public String canDragRecordsOut;
    public String canDropOnLeaves;
    public String canReorderRecords;
    public String canReparentNodes;
    public String cantDragIntoChildMessage;
    public String cantDragIntoSelfMessage;
    public String cascadeSelection;
    public String closedIconSuffix;
    public String connectorImage;
    public String createDefaultTreeField;
    public String customIconDropProperty;
    public String customIconOpenProperty;
    public String customIconProperty;
    public String dataFetchMode;
    public DataSource dataSourceAsDataSource;
    public String dataSourceAsString;
    public String displayNodeType;
    public String dropIconSuffix;
    public String extraIconGap;
    public TreeGridField[] fields;
    public String folderIcon;
    public String iconSize;
    public String indentRecordComponents;
    public String indentSize;
    public TreeNode[] initialData;
    public String keepParentsOnFilter;
    public String leaveSelectionCheckboxGap;
    public String loadDataOnDemand;
    public String manyItemsImage;
    public String nodeIcon;
    public String offlineNodeMessage;
    public String openerIconSize;
    public String openerImage;
    public String openIconSuffix;
    public String parentAlreadyContainsChildMessage;
    public String selectionProperty;
    public String separateFolders;
    public String[] serverFilterFields;
    public String showConnectors;
    public String showCustomIconDrop;
    public String showCustomIconOpen;
    public String showDisabledSelectionCheckbox;
    public String showDropIcons;
    public String showFullConnectors;
    public String showOpener;
    public String showOpenIcons;
    public String showPartialSelection;
    public String showRoot;
    public String sortFoldersBeforeLeaves;
    public String treeFieldTitle;
    public String treeRootValue;
    public String useAllDataSourceFields;
}



