package com.smartgwt.logicalstructure.widgets.form;
import com.smartgwt.client.core.*;
import com.smartgwt.client.rpc.*;
import com.smartgwt.client.i18n.*;
import com.smartgwt.client.event.*;
import com.smartgwt.client.util.*;
import com.smartgwt.client.util.workflow.*;
import com.smartgwt.client.types.*;
import com.smartgwt.client.data.*;
import com.smartgwt.client.data.fields.*;
import com.smartgwt.client.widgets.*;
import com.smartgwt.client.widgets.calendar.*;
import com.smartgwt.client.widgets.chart.*;
import com.smartgwt.client.widgets.cube.*;
import com.smartgwt.client.widgets.drawing.*;
import com.smartgwt.client.widgets.form.*;
import com.smartgwt.client.widgets.form.fields.*;
import com.smartgwt.client.widgets.form.validator.*;
import com.smartgwt.client.widgets.grid.*;
import com.smartgwt.client.widgets.layout.*;
import com.smartgwt.client.widgets.menu.*;
import com.smartgwt.client.widgets.plugins.*;
import com.smartgwt.client.widgets.tab.*;
import com.smartgwt.client.widgets.tableview.*;
import com.smartgwt.client.widgets.tile.*;
import com.smartgwt.client.widgets.toolbar.*;
import com.smartgwt.client.widgets.tree.*;
import com.smartgwt.client.widgets.viewer.*;
import com.smartgwt.logicalstructure.core.*;
import com.smartgwt.logicalstructure.widgets.*;
import com.smartgwt.logicalstructure.widgets.form.*;
import com.smartgwt.logicalstructure.widgets.tile.*;
import com.smartgwt.logicalstructure.widgets.grid.*;
import com.smartgwt.logicalstructure.widgets.chart.*;
import com.smartgwt.logicalstructure.widgets.layout.*;
import com.smartgwt.logicalstructure.widgets.menu.*;
import com.smartgwt.logicalstructure.widgets.tab.*;
import com.smartgwt.logicalstructure.widgets.toolbar.*;
import com.smartgwt.logicalstructure.widgets.tree.*;
import com.smartgwt.logicalstructure.widgets.viewer.*;
import com.smartgwt.logicalstructure.widgets.calendar.*;
import com.smartgwt.logicalstructure.widgets.cube.*;
import com.smartgwt.logicalstructure.widgets.drawing.*;

public class DynamicFormLogicalStructure extends CanvasLogicalStructure {
    public String action;
    public String allowExpressions;
    public String autoFocus;
    public String browserSpellCheck;
    public String cancelParamName;
    public String cancelParamValue;
    public String canEdit;
    public String canEditFieldAttribute;
    public String canFocus;
    public String canSubmit;
    public String canTabToSectionHeaders;
    public String cellBorder;
    public String cellPadding;
    public String clipItemTitles;
    public String colWidths;
    public String dataFetchMode;
    public String dateFormatter;
    public String datetimeFormatter;
    public String disableValidation;
    public String encoding;
    public String errorItemCellStyle;
    public String errorOrientation;
    public String errors;
    public String errorsPreamble;
    public String[] fields;
    public String fixedColWidths;
    public String formSubmitFailedWarning;
    public String hiliteRequiredFields;
    public String implicitSave;
    public String implicitSaveDelay;
    public String implicitSaveOnBlur;
    public String itemHoverAlign;
    public String itemHoverDelay;
    public String itemHoverHeight;
    public String itemHoverOpacity;
    public String itemHoverStyle;
    public String itemHoverVAlign;
    public String itemHoverWidth;
    public String itemLayout;
    public String[] items;
    public String longTextEditorThreshold;
    public String longTextEditorType;
    public String method;
    public String minColWidth;
    public String numCols;
    public String operator;
    public String rejectInvalidValueOnChange;
    public String requiredMessage;
    public String requiredRightTitlePrefix;
    public String requiredRightTitleSuffix;
    public String requiredTitlePrefix;
    public String requiredTitleSuffix;
    public String rightTitlePrefix;
    public String rightTitleSuffix;
    public String saveOnEnter;
    public String saveOperationType;
    public String sectionVisibilityMode;
    public String selectOnClick;
    public String selectOnFocus;
    public String showComplexFieldsRecursively;
    public String showDetailFields;
    public String showErrorIcons;
    public String showErrorStyle;
    public String showErrorText;
    public String showInlineErrors;
    public String showTitlesWithErrorMessages;
    public String stopOnError;
    public String suppressValidationErrorCallback;
    public String synchronousValidation;
    public String target;
    public String timeFormatter;
    public String titleAlign;
    public String titleOrientation;
    public String titlePrefix;
    public String titleSuffix;
    public String titleWidthAsString;
    public String unknownErrorMessage;
    public UserTask userTask;
    public String validateOnChange;
    public String validateOnExit;
    public String validationURL;
    public String values;
    public String wrapItemTitles;
}


